window.sgCell = {
  name: "一代测序111111",
  row: 100,
  column: 0,
  columnHeaderArr: ['爱', '我', '中', '华', 5, 2, 0, 1, 2, 3, 4],
  defaultColWidth: 150,
  defaultRowHeight: 40,
  celldata: [
    {
      r: 0,
      c: 0,
      v: {
        ct: { fa: "General", t: "g" },
        m: "value1",
        v: "value1",
      },
    },
    {
      r: 0,
      c: 1,
      v: {
        ct: { fa: "General", t: "g" },
        m: "value2",
        v: "value2",
      },
    },
  ],
  config: {
    merge: {
      "6_5": {
        r: 6,
        c: 5,
        rs: 2,
        cs: 2,
      },
    },
    rowlen: {
      0: 30,
      1: 30,
    },
    columnlen: {
      0: 100,
      1: 100,
    },
    borderInfo: [
      {
        rangeType: "cell",
        value: {
          row_index: 3,
          col_index: 3,
          l: {
            style: 7,
            color: "#FF0000",
          },
          r: {
            style: 7,
            color: "#FF0000",
          },
          t: {
            style: 7,
            color: "#FF0000",
          },
          b: {
            style: 7,
            color: "#FF0000",
          },
        },
      },
      {
        rangeType: "range",
        borderType: "border-all",
        style: 7,
        color: "#ff0000",
        range: [
          {
            row: [6, 7],
            column: [5, 6],
          },
        ],
      },
    ],

    scrollLeft: 0,
    scrollTop: 0,

    // frozen: [
    //   {
    //     type: "rangeColumn",
    //     range: { c },
    //   },
    // ],
  },
  // 冻结单元格
  // frozen: {
  //   type: "rangeColumn",
  //   range: { row_focus: 1, column_focus: 5 },
  // },

  dataVerification: {
    /* 下拉框 */
    "1_0": {
      type: "dropdown",
      type2: null,
      value1: "Develop,Fix,Done",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "2_0": {
      type: "dropdown",
      type2: null,
      value1: "Develop,Fix,Done",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "3_0": {
      type: "dropdown",
      type2: null,
      value1: "Develop,Fix,Done",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "4_0": {
      type: "dropdown",
      type2: null,
      value1: "Develop,Fix,Done",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "5_0": {
      type: "dropdown",
      type2: null,
      value1: "Develop,Fix,Done",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "6_0": {
      type: "dropdown",
      type2: null,
      value1: "Develop,Fix,Done",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    /* 下拉框 End */
    /* 复选框 */
    "1_1": {
      type: "checkbox",
      type2: null,
      value1: "Pass",
      value2: "Fail",
      checked: false,
      remote: true,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "2_1": {
      type: "checkbox",
      type2: null,
      value1: "Pass",
      value2: "Fail",
      checked: true,
      remote: true,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "3_1": {
      type: "checkbox",
      type2: null,
      value1: "Pass",
      value2: "Fail",
      checked: false,
      remote: true,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "4_1": {
      type: "checkbox",
      type2: null,
      value1: "Pass",
      value2: "Fail",
      checked: false,
      remote: true,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "5_1": {
      type: "checkbox",
      type2: null,
      value1: "Pass",
      value2: "Fail",
      checked: false,
      remote: true,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "6_1": {
      type: "checkbox",
      type2: null,
      value1: "Pass",
      value2: "Fail",
      checked: true,
      remote: true,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    /* 复选框 End */
    /* 复选框 */
    "1_2": {
      type: "number",
      type2: "bw",
      value1: "1",
      value2: "10",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "2_2": {
      type: "number",
      type2: "bw",
      value1: "1",
      value2: "10",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "3_2": {
      type: "number",
      type2: "bw",
      value1: "1",
      value2: "10",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "4_2": {
      type: "number",
      type2: "bw",
      value1: "1",
      value2: "10",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "5_2": {
      type: "number",
      type2: "bw",
      value1: "1",
      value2: "10",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "6_2": {
      type: "number",
      type2: "bw",
      value1: "1",
      value2: "10",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    /* 复选框 */
    /* 复选框 End */
    "1_3": {
      type: "text_content",
      type2: "include",
      value1: "MBLsheet",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: true,
      hintText: "include MBLsheet",
    },
    "2_3": {
      type: "text_content",
      type2: "include",
      value1: "MBLsheet",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: true,
      hintText: "include MBLsheet",
    },
    "3_3": {
      type: "text_content",
      type2: "include",
      value1: "MBLsheet",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: true,
      hintText: "include MBLsheet",
    },
    "4_3": {
      type: "text_content",
      type2: "include",
      value1: "MBLsheet",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: true,
      hintText: "include MBLsheet",
    },
    "5_3": {
      type: "text_content",
      type2: "include",
      value1: "MBLsheet",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: true,
      hintText: "include MBLsheet",
    },
    "6_3": {
      type: "text_content",
      type2: "include",
      value1: "MBLsheet",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: true,
      hintText: "include MBLsheet",
    },
    /* 包含框 */
    /* 复选框 */
    "1_4": {
      type: "text_length",
      type2: "bw",
      value1: "1",
      value2: "5",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "2_4": {
      type: "text_length",
      type2: "bw",
      value1: "1",
      value2: "5",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "3_4": {
      type: "text_length",
      type2: "bw",
      value1: "1",
      value2: "5",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "4_4": {
      type: "text_length",
      type2: "bw",
      value1: "1",
      value2: "5",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "5_4": {
      type: "text_length",
      type2: "bw",
      value1: "1",
      value2: "5",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    "6_4": {
      type: "text_length",
      type2: "bw",
      value1: "1",
      value2: "5",
      checked: false,
      remote: false,
      prohibitInput: true,
      hintShow: false,
      hintText: "",
    },
    /* 包含框 */
    /* 比较框 */
    "1_5": {
      type: "date",
      type2: "bw",
      value1: "2020-09-23",
      value2: "2020-10-10",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "2_5": {
      type: "date",
      type2: "bw",
      value1: "2020-09-23",
      value2: "2020-10-10",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "3_5": {
      type: "date",
      type2: "bw",
      value1: "2020-09-23",
      value2: "2020-10-10",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "4_5": {
      type: "date",
      type2: "bw",
      value1: "2020-09-23",
      value2: "2020-10-10",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "5_5": {
      type: "date",
      type2: "bw",
      value1: "2020-09-23",
      value2: "2020-10-10",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "6_5": {
      type: "date",
      type2: "bw",
      value1: "2020-09-23",
      value2: "2020-10-10",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    /* 比较框 End */
    /* 校验身份证 */
    "1_6": {
      type: "validity",
      type2: "card",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "2_6": {
      type: "validity",
      type2: "card",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "3_6": {
      type: "validity",
      type2: "card",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "4_6": {
      type: "validity",
      type2: "card",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "5_6": {
      type: "validity",
      type2: "card",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "6_6": {
      type: "validity",
      type2: "card",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    /* 校验身份证 End */
    /* 校验手机号 */
    "1_7": {
      type: "validity",
      type2: "phone",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "2_7": {
      type: "validity",
      type2: "phone",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "3_7": {
      type: "validity",
      type2: "phone",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "4_7": {
      type: "validity",
      type2: "phone",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "5_7": {
      type: "validity",
      type2: "phone",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    "6_7": {
      type: "validity",
      type2: "phone",
      value1: "",
      value2: "",
      checked: false,
      remote: false,
      prohibitInput: false,
      hintShow: false,
      hintText: "",
    },
    /* 校验手机号 End */
  },
};
// export default sheetCell
